- 인공 뉴런
  - 신경 세포 구조를 단순화하여 모델링한 구조
  - 노드와 엣지로 표현
  - 하나의 노드안에서 입력과 가중치를 곱하고 더하는 선형 구조
  - 활성화 함수를 통한 비선형 구조 표현 가능

- 인공 신경망
  - 여러 개의 인공뉴런들이 모여 연결된 형태
  - 뉴런들이 모인 하나의 단위를 layer라고 하고, multi layer으로 이루어질 수 있음
  - input layer, hidden layer, output layer

## Tensorflow
- 가장 널리 쓰이는 딥러닝 프레임워크 중 하나
- 구글이 주도적으로 개발하는 플랫폼
- 파이썬, c++ api를 기본적으로 제공하며 js, java, go, swift 등 다양한 언어 지원
- tf.keras를 중심으로 고수준 api 통합
- TPU(tensor processing unit)지원
   - TPU는 GPU보다 전력을 적게 소모, 경제적
   - 일반적으로 32비트(float32)로 수행되는 곱셈 연산을 16비트(float16)로 낮춤


## Keras
- python으로 작성된 고수준 신경망 API로 tensorflow, CNTK, Theano와 함께 사용가능
- 사용자 친화성, 모듈성, 확장성을 통해 빠르고 간편한 프로토타이핑 가능
- 컨볼루션 신경망, 순환 신경망, 그리고 둘의 조합까지 모두 지원
- CPU, GPU에서 매끄럽게 실행


## 딥러닝 데이터 표현과 연산
- 데이터 표현을 위한 기본 구조로 텐서(tensor)를 사용
- 텐서는 데이터를 담기위한 컨테이너로서 일반적으로 수치형 데이터를 저장.

## 텐서
- Rank: 축의 개수
- shape: 형상 (각 축에 따른 차원 개수)
- type: 데이터 타입


In [ ]:
import numpy as np
import tensorflow as tf

0D tensor(scalar)
- 하나의 숫자를 담고있는 텐서
- 축과 형상이 없음

In [ ]:
t0 = tf.constant(1)
print(t0)
print(tf.rank(t0))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


1D tensor(vector)
- 값들을 저장한 리스트와 유사한 텐서
- 하나의 축이 존재

In [ ]:
t1 = tf.constant([1, 2, 3])
print(t1)
print(tf.rank(t1))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


2D tensor(matrix)
- 행렬과 같은 모양으로 두개의 축이 존재
- 일반적인 수치, 통계 데이터셋이 해당
- 주로 샘플(sample)과 특성(features)을 가진 구조로 사용

In [ ]:
t2 = tf.constant([[1,2,3], [1,2,3], [7,8,9]])
print(t2)
print(tf.rank(t2))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


3D tensor
- cube와 같은 모양으로 세개의 축이 존재
- 데이터가 연속된 시퀀스 데이터나 시간 축이 포함된 시계열 데이터에 해당
- 주식 가격 데이터셋, 시간에 따른 질병 발병 데이터 등이 존재
- 주로 samples, timesteps, features를 가진 구조로 사용

In [ ]:
t3 = tf.constant([[[1,2,3],[4,5,6], [7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6], [7,8,9]]])
print(t3)
print(tf.rank(t3))

tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]], shape=(3, 3, 3), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


4D tensor
- 4개의 축
- 컬러 이미지 데이터가 대표적인 사례 (흑백 이미지 데이터는 3d tensor로 가능)
- 주로 samples, height, width, channel을 가진 구조로 사용

5D tensor
- 5개의 축
- 비디오 데이터가 대표적인 사례
- 주로 samples, frames, height, width, channel을 가진 구조로 사용


## 텐서 데이터 타입
- 텐서의 기본 dtype
  - 정수형 텐서: int32
  - 실수형 텐서: float32
  - 문자열 텐서: string
- int32, float32, string타입 외에도 float16, int8 타입 등이 존재
- 연산시 텐서의 타입 일치 필요
- 타입변환에는 tf.cast() 사용