# numpy의 연산과 함수
### numpy의 기본 연산
- numpy는 배열에 대한 기본적인 사칙연산을 지원.

In [2]:
import numpy as np
array = np.random.randint(1, 10, size=4).reshape(2, 2)
print(array)

[[9 1]
 [1 2]]


In [3]:
result_array = array * 10
print(result_array)

[[90 10]
 [10 20]]


### 서로 다른 형태의 numpy 연산
- numpy는 서로 다른 형태의 배열을 연산할 때는 행 우선으로 수행됨.

In [5]:
import numpy as np
array1 = np.arange(4).reshape(2, 2)
array2 = np.arange(2) # (1 x 2)

array3 = array1 + array2

print(array3)

[[0 2]
 [2 4]]


### 서로 다른 형태의 numpy 연산
- 브로드캐스트: 형태가 다른 배열을 연산할 수 있도록 배열의 형태를 동적으로 변환

In [8]:
import numpy as np

array1 = np.arange(0, 8).reshape(2, 4)
array2 = np.arange(0, 8).reshape(2, 4)
array3 = np.concatenate([array1, array2], axis = 0)

# broadcast
array4 = np.arange(0, 4).reshape(4, 1) # (4 x 1)

print(array3)
print(array4)
print("\n")
print(array3 + array4)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[0]
 [1]
 [2]
 [3]]


[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


### numpy의 마스킹 연산
- 마스킹: 각 원소에 대하여 체크.

In [12]:
import numpy as np

array1 = np.arange(16).reshape(4,4)
print(array1)

array2 = array1 < 10
print(array2)

array1[array2] = 100
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


### numpy의 집계함수

In [14]:
import numpy as np
array = np.arange(16).reshape(4, 4)

print("max: ", np.max(array))
print("min: ", np.min(array))
print("sum: ", np.sum(array))
print("mean: ", np.mean(array))

max:  15
min:  0
sum:  120
mean:  7.5


In [19]:
print(array)
print("\n")
print(np.sum(array, axis = 0))
print(np.sum(array, axis = 1).reshape(4, 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[24 28 32 36]
[[ 6]
 [22]
 [38]
 [54]]
