# Numpy의 기본 사용법
numpy란?
- numpy는 다차원 배열을 효과적으로 처리할 수 있도록 도와주는 도구.
- 현실 세계의 다양한 데이터는 배열형태로 표현할 수 있음.
- python의 기본 list에 비해 빠르고 강력한 기능 제공.

numpy의 차원
- 1차원 축(행): axis 0 => vector
- 2차원 축(열): axis 1 => matrix
- 3차원 축(채널): axis 2 => tensor(3차원이상)

In [2]:
import numpy as np
list_data = [1, 2, 3]
array = np.array(list_data)

print(list_data)
print(array)
print(array.size)
print(array.dtype)

[1, 2, 3]
[1 2 3]
3
int64


In [5]:
 # numpy 배열 초기화하기

 # 0~3까지의 배열 만들기
array1 = np.arange(4)
array2 = np.zeros((4,4), dtype=float)
array3 = np.ones((3,3), dtype=str)

 # 0~9까지 랜덤하게 초기화 된 배열 만들기
array4= np.random.randint(0, 10, (3,3))

# 평균이 0이고 표준편차가 1인 표준 정규를 띄는 배열
array5 = np.random.normal(0, 1, (3,3))

print(array1)
print(array2)
print(array3)
print(array4)
print(array5)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]
[[0 4 0]
 [6 8 0]
 [2 7 3]]
[[ 0.00430875 -0.07980629  0.7651938 ]
 [ 0.68177594 -0.24398047 -1.61959329]
 [ 0.67454651  0.03107336 -0.22661805]]


In [6]:
# numpy 배열 합치기 
## ex ) 1 + 2 + 3 = 123
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.concatenate([array1, array2])

print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


In [8]:
# numpy 배열 형태 바꾸기
import numpy as np

array1 = np.array([1, 2, 3, 4])
array2 = array1.reshape((2, 2))

print(array1)
print(array2.shape)
print(array2)

[1 2 3 4]
(2, 2)
[[1 2]
 [3 4]]


In [12]:
# numpy 배열 세로 축으로 합치기

array1 = np.arange(4).reshape(1, 4)
array2 = np.arange(8).reshape(2, 4)

print(array1, "\n", array2)
print("\n")

array3 = np.concatenate([array1, array2], axis = 0)
print(array3.shape)
print(array3)

[[0 1 2 3]] 
 [[0 1 2 3]
 [4 5 6 7]]


(3, 4)
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


In [13]:
# numpy 배열 나누기
import numpy as np

array = np.arange(8).reshape(2, 4)
left, right = np.split(array, [2], axis =1)
print(left.shape)
print(left)
print("\n")
print(right.shape)
print(right)

(2, 2)
[[0 1]
 [4 5]]


(2, 2)
[[2 3]
 [6 7]]


In [14]:
# numpy 배열 상하로 나누기
import numpy as np
array = np.arange(8).reshape(2, 4)
up, down = np.split(array, [1], axis =0)
print(up.shape)
print(up)
print("\n")
print(down.shape)
print(down)

(1, 4)
[[0 1 2 3]]


(1, 4)
[[4 5 6 7]]
